apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: yukukaru23/udagram-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-srv
spec:
  selector:
    app: frontend-app
  ports:
    - name: frontend-app-srv
      protocol: TCP
      port: 8080
      targetPort: 8080

