apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-app
  labels:
    app: reverseproxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy-app
  template:
    metadata:
      labels:
        app: reverseproxy-app
    spec:
      containers:
      - name: reverseproxy
        image: yukukaru23/reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-app-srv
spec:
  selector:
    app: reverseproxy-app
  ports:
    - name: reverseproxy-app-srv
      protocol: TCP
      port: 8080
      targetPort: 8080